Update AppHead.js
Differential/chase-oaks-apollos-tv pull request #13
Opened 2022-04-26 19:57 UTC by leungwaynetx

Adding set session event for Crisp chatbot

### About

### Testing

### Screenshots
N/A

2022-04-26 21:43 UTC, conrad-vanl commented
hey @leungwaynetx are you familiar with linting at all? This PR is failing right now due to a linter error. It should be easy to fix if you know how to discover the lint error. `yarn lint` should show you if you were running the code locally at all.

If not, then I can potentially figure another way to help. 

I tried adding a `lint` action to our GitHub actions so that GitHub will actually show you the lint error on this PR (and they make it super easy to fix the error) but I don't think you'll see that action run until you push at least one more commit up.

Edit: if you're not familiar with linting, it's just an automated tool we use to make sure your code follows consistent syntax/formatting rules. That way we don't end up with different blocks of code formatted differently. Looking at the error, I think you just need to space out the code you added a little differently to make the linter happy.

2022-04-26 23:41 UTC, leungwaynetx commented
Thanks again Conrad. Sorry that I am a total noob here and using so much of your time. I really do appreciate your kind help and advice. Does the above commentary mean the linter was executed(??) upon my last commit (I tried to match the syntax to the similar line below my insert). Thanks again, Wayne

2022-04-27 14:12 UTC, conrad-vanl requested changes

2022-04-27 14:12 UTC, conrad-vanl commented on tvappweb/components/AppHead/AppHead.js
> +    window.$crisp.push(['set', 'session:event', [[['chaseoakstv:page:loaded', {}, 'red']]]]);
```suggestion
    window.$crisp.push([
      'set',
      'session:event',
      [[['chaseoakstv:page:loaded', {}, 'red']]],
    ]);
```

@leungwaynetx FYI, our linter is wanting it to be formatted like this - it's supposed to automatically add these suggestions to the PR but for some reason that's not working, so I've added the code suggestion manually in this comment.

You should be able to accept the suggestion above and the PR checks will re-run and then we should be good to go.

2022-04-27 14:19 UTC, leungwaynetx commented
Thanks Conrad. I will get smarter as we go forward... I promise.

2022-04-27 14:21 UTC, leungwaynetx commented
Commited

2022-04-27 22:33 UTC, conrad-vanl approved these changes

2022-04-27 22:34 UTC, conrad-vanl commented
Hey @leungwaynetx please stop apologizing/feeling bad. You're doing great. 

There's a Preview URL available of your work here:
https://chase-oaks-apollos-83de97ou8-apollos.vercel.app

If you want to test to see that what you did is working, you can do so at that URL.

I've approved this PR based on a code review. I'll let you confirm that everything is working as you intend it to on that URL, and once you give me the 👍 I'll merge it and it'll get deployed to the live website.

2022-04-29 13:13 UTC, conrad-vanl commented
@leungwaynetx since you're an "outside" collaborator I have to push a button on GitHub to give it permission to run its checks and deploy a testing url. I just did that for your last commit and you can see that in the status history:
<img width="749" alt="Screen Shot 2022-04-29 at 8 13 00 AM" src="https://user-images.githubusercontent.com/103927/165951164-77c0c12f-b44e-4d5e-9af2-e51a4f36b86a.png">

So just give me an @ mention whenever you need me to press the button so you can test your work, it's no problem.

https://chase-oaks-apollos-iiyxwnk45-apollos.vercel.app

2022-04-29 20:27 UTC, leungwaynetx commented
@conrad-vanl , The testing was successful. Ready to merge whenever you are ok and ready to deploy as well. Thanks - Wayne

2022-05-03 20:37 UTC, merged

2022-05-03 20:37 UTC, conrad-vanl commented
Merged. Should auto deploy shortly.

2022-05-04 18:22 UTC, leungwaynetx commented
Thanks Conrad!

On Tue, May 3, 2022 at 3:37 PM Conrad VanLandingham <
***@***.***> wrote:

> Merged. Should auto deploy shortly.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Differential/chase-oaks-apollos-tv/pull/13#issuecomment-1116587505>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY46LQWVWZXT6IEWQGF6C43VIGFATANCNFSM5UM5SLOA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>